### ISSUE TITLE
Add Vivaldi browser

### ISSUE THREAD

**Issue by tomlutzenberger** [godban/browsers-support-badges#5]
Eventhough it's new, Vivaldi made a rocket-like start.
I can submit a PR if you want me to.

**Comment by godban** [comment]
Hey @tomlutzenberger, thanks for proposal.
Yea, why not. Would be appreciate for PR.

**Comment by tomlutzenberger** [comment]
Made the changes but wasn't able to build and test because some dependencies are not compatible with Ubuntu. I will try later in the evening on Windows.

**Comment by godban** [comment]
@tomlutzenberger no worries, you can send it as it is. I didn't update project for a while, will do some work on top anyway.

**Comment by tomlutzenberger** [comment]
Oh okay, that's nice.
In case you think about a redesign or similar: I made some browser badges myself in a [project](https://github.com/tomlutzenberger/adminBookmark).

**Comment by godban** [comment]
Released PR changes
